name: ClickCrystalsAlias
version: '${version}'
main: me.trouper.clickcrystalsalias.ClickCrystalsAlias
api-version: 1.20
authors: [ obvWolf ]
description: Various utils for ClickCrystals.xyz
commands:
  cca:
    usage: /cca
    permission: cca.admin
  spawn:
    usage: /spawn
  discord:
    usage: /discord
  vulcanban:
    permission: cca.admin
  box:
    usage: /box
  autokit:
    usage: /autokit <integer>
    aliases: /ak
permissions:
  cca.admin:
    description: admid